### ISSUE TITLE
在5.15内核环境下午无法使用

### ISSUE THREAD

**Issue by 596142041** [ZeaKyX/luci-app-speedtest-web#1]
![image](https://user-images.githubusercontent.com/4958182/155846046-cd057de2-3b97-42ba-865c-26255c8d2870.png)
![image](https://user-images.githubusercontent.com/4958182/155846053-e0ab965d-8be8-415a-8725-23dddd5874ab.png)
在软件包里面已经看见了，但是没有这选项，这怎么修复呢

**Comment by ZeaKyX** [comment]
应该重启过了吧
需要检查一下speedtest-web进程有没有启动
看看启动项里重启，有没有日志
或则终端里手动运行speetest-web
我现在没有环境测试

**Comment by ZeaKyX** [comment]
虚拟机测试5.15.25内核没有问题
![image](https://user-images.githubusercontent.com/43315078/156316377-e5232152-cf1b-4d6a-9980-527a8cb63400.png)
